# Generated by Django 3.1.4 on 2020-12-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShowsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShowTitle', models.CharField(max_length=100, verbose_name='Title')),
                ('ShowImage', models.URLField(verbose_name='Poster Image')),
                ('ShowTrailer', models.URLField(blank=True, verbose_name='Trailer')),
                ('Banner', models.BooleanField(default=False)),
                ('Popular', models.BooleanField(default=False)),
                ('ShowDesc', models.TextField(verbose_name='Description')),
                ('ShowReleaseDate', models.DateTimeField(verbose_name='Release Date')),
                ('Audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audio', to='shows.language')),
                ('Genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genre', to='shows.genres', verbose_name='Category')),
                ('SubTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubTitle', to='shows.subtitles', verbose_name='Sub Titles')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Platform', to='shows.platform')),
            ],
            options={
                'verbose_name': 'Show Lists',
                'verbose_name_plural': 'Show List',
            },
        ),
        migrations.CreateModel(
            name='SeasonsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeasonTitle', models.CharField(max_length=15)),
                ('SeasonDesc', models.TextField()),
                ('SeasonImage', models.URLField()),
                ('SeasonTrailer', models.URLField(blank=True)),
                ('SeasonReleaseDate', models.DateTimeField()),
                ('Series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Series', to='shows.showslist')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EpisodeTitle', models.CharField(max_length=100)),
                ('EpisodeDesc', models.TextField()),
                ('EpisodeLink', models.URLField()),
                ('EpisodeReleaseDate', models.DateTimeField()),
                ('Season', models.ManyToManyField(limit_choices_to={'Series': True}, related_name='Season', to='shows.SeasonsList')),
                ('Show', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Show', to='shows.showslist')),
            ],
        ),
    ]
