# Generated by Django 3.1.4 on 2020-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodelist',
            name='Season',
            field=models.ManyToManyField(related_name='Season', to='shows.SeasonsList'),
        ),
    ]
