# Generated by Django 3.1.4 on 2020-12-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20201209_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodelist',
            name='Season',
            field=models.ManyToManyField(limit_choices_to={'Series': True}, related_name='Season', to='shows.SeasonsList'),
        ),
    ]
