# Generated by Django 3.1.4 on 2020-12-13 11:11

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20201209_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodelist',
            name='Season',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='Show', chained_model_field='Series', horizontal=True, related_name='Season', to='shows.SeasonsList'),
        ),
    ]
