# Generated by Django 3.1.4 on 2020-12-23 07:38

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20201213_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodelist',
            options={'verbose_name': 'Episodes', 'verbose_name_plural': 'Episode'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Languages', 'verbose_name_plural': 'Language'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platforms', 'verbose_name_plural': 'Platform'},
        ),
        migrations.AlterModelOptions(
            name='seasonslist',
            options={'verbose_name': 'Seasons', 'verbose_name_plural': 'Season'},
        ),
        migrations.AlterModelOptions(
            name='showslist',
            options={'verbose_name': 'Shows', 'verbose_name_plural': 'Show'},
        ),
        migrations.AlterModelOptions(
            name='subtitles',
            options={'verbose_name': 'SubTitles', 'verbose_name_plural': 'SubTitle'},
        ),
        migrations.RemoveField(
            model_name='episodelist',
            name='Season',
        ),
        migrations.AddField(
            model_name='episodelist',
            name='Season',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Show', chained_model_field='Series', default='', on_delete=django.db.models.deletion.CASCADE, to='shows.seasonslist'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genres',
            field=models.CharField(max_length=50, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Audio Title'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Platform Title'),
        ),
        migrations.AlterField(
            model_name='subtitles',
            name='subTitle',
            field=models.CharField(max_length=50, verbose_name='Sub Title'),
        ),
    ]
